include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    prefer_const_constructors: flase
    prefer_const_literals_to_create_immutables: flase
    prefer_const_constructors_in_immutables: flase
